### ISSUE TITLE
JAGS 4.3.0 does not work with bbsBayes

### ISSUE THREAD

**Issue by BrandonEdwards** [BrandonEdwards/bbsBayes#127]
One of the issues that gave us grief for a LONG time (see #91) has turned out to be an issue with JAGS 4.3.0 not working with the models used by bbsBayes. For whatever reason, when running the slope model (and looks like GAM models too, FD is untested), beta[] and BETA parameters absolutely struggle to converge. This problem does not exist on 4.2.0. This issue has been replicated across multiple machines running various OS. 

We are currently seeking the assistance of Martyn Plummer (creator of JAGS) on this issue. See https://martynplummer.wordpress.com/2017/07/18/jags-4-3-0-is-released/#comment-2614 for updates.

**Comment by AdamCSmithCWS** [comment]
THis is now totally solved. It was the "glm" module in JAGS causing the weird issues. The modules = NULL argument in the run_model function solves this.
