### ISSUE TITLE
deprecate generate_regional_indices() and deprecate_regional_trends()

### ISSUE THREAD

**Issue by BrandonEdwards** [BrandonEdwards/bbsBayes#152]
Since we are going ahead with #147 and #148 it no longer makes sense to add a spatial qualifier to this function (i.e. the "regional"). Instead, deprecate in favour of "generate_indices()" and "generate_trends()"

**Comment by AdamCSmithCWS** [comment]
agreed

Adam C. Smith

Senior Biostatistician, Wildlife Monitoring and Assessment, Canadian Wildlife Service
Environment and Climate Change Canada, Government of Canada
Adam.Smith2@canada.ca<mailto:Adam.Smith2@canada.ca> /Tel: 613-998-0485

Biostatistician Principal, Évaluation et Surveillance des Espéces Sauvages, Service canadien de la faune
Environnement et Changement Climatique Canada, Gouvernement du Canada
Adam.Smith2@canada.ca<mailto:Adam.Smith@ec.gc.ca> /Tel: 613-998-0485
