### ISSUE TITLE
Clarify progress notification messages in `run_model()`

### ISSUE THREAD

**Issue by trashbirdecology** [BrandonEdwards/bbsBayes#158]
Although you clarify in readme that `run_model()` "takes a long time", the status message could use some more information. The first message I see for at least a few minutes after running this function is:
```
Processing function input....... 
Done. 

``` 
... and although the function is still processing, I see the word "Done" for some time. 

I suggest improving the information in the message to clarify the state of the process. Perhaps adding something between
```
Done.
``` 

and 
```
Compiling model graph 
```

**Comment by BrandonEdwards** [comment]
I believe this is the default messaging from the JAGS packages (jagsUI) that are used in this package. That is, when you start up a JAGS model, the jagsUI package sends these messages to the console.

I may consider looking into a way to override jagsUI messages, however, and substitute with our own, more useful messages!
