### ISSUE TITLE
add a function to extract the strata maps

### ISSUE THREAD

**Issue by AdamCSmithCWS** [BrandonEdwards/bbsBayes#167]
for example, something simple like:

library(sf)
locat = system.file("maps",
            package="bbsBayes")
map.file = "BBS_CWS_strata"

bbs_strata_map = sf::read_sf(dsn = locat,
                         layer = map.file)

The package includes shapefiles relating to each of the stratification options. These shapefiles are used to produce the trend maps, and they provide the underlying spatial information for the area-weights that help to integrate predictions across strata to provide predictions for the broader regions (e.g., continental, national, provincial, etc.). 
It would be useful if there was an easy way to load these shapefiles into the R-session, so that users can customize their mapping using the package results.

This could relate to issue #170

**Comment by trashbirdecology** [comment]
@AdamCSmithCWS, can you elaborate on this issue? As someone not intimately familiar with the package, I am having trouble deciphering your feature request. I am assuming this is one of the maps produced as an analysis result?

**Comment by AdamCSmithCWS** [comment]
Yes @trashbirdecology . Good point, thanks.
In the package, there are shapefiles relating to each of the stratification options. I'll edit the original.

**Comment by BrandonEdwards** [comment]
#183 solves this
