### ISSUE TITLE
`stratify()` with `lump_species_forms` duplicates non-unidentified birds

### ISSUE THREAD

**Issue by steffilazerte** [BrandonEdwards/bbsBayes#195]
I've been 'tidying' the stratify function and have found what I think is a bug?

I looks like when lumping species together, the observations for species which were *not* unidentified, become duplicated, with two different AOU codes. The species which were unidentified are not duplicated.

For example, when lumping 2970 (Dusky Grouse) and 2971 (Sooty Grouse) into 2973 (Blue Grouse (Dusky/Sooty)), we end up with two observations (`s` data set is stratified) when we formally had just one (`bbs_data` is raw data):

```
> dplyr::filter(bbs_data$bird, AOU %in% c(2970, 2971, 2973), RouteDataID == 6214132)
RouteDataID countrynum statenum Route  RPID  Year   AOU Count10 Count20 Count30 Count40 Count50 StopTotal SpeciesTotal   BCR
1   6214132        124       11     1   101  1991  2971       0       0       0       1       0         1            1     5

> dplyr::filter(s$bird_strat, AOU %in% c(2970, 2971, 2973), RouteDataID == 6214132)
         statenum Route countrynum RouteDataID RPID Year  AOU Count10 Count20 Count30 Count40 Count50 StopTotal
498            11     1        124     6214132  101 1991 2971       0       0       0       1       0         1
49810000       11     1        124     6214132  101 1991 2973       0       0       0       1       0         1
         SpeciesTotal BCR rt.uni  rt.uni.y
498                 1   5   11-1 11-1-1991
49810000            1   5   11-1 11-1-1991
```

**Can I assume that the lumping of bird forms should result in all observations of 2970, 2971, and 2973 should become 2973 (and so on for the names as well as other species to be lumped together), and this applies the `species` and `bird` data frames?**

**Comment by AdamCSmithCWS** [comment]
That should be a feature (not a bug), if I understand correctly. The idea was to provide a combined species (2973), while still retaining the original separate species. It allows the user to analyse the separate species or to analyse a combined all Dusky and Sooty grouse.

**Comment by steffilazerte** [comment]
Ah, good! Thanks! So the idea would be that if the user wanted the combined species, they would specify a species as "Blue Grouse (Dusky/Sooty))" later on in the `prepare_data()` stage?

**Comment by AdamCSmithCWS** [comment]
> Ah, good! Thanks! So the idea would be that if the user wanted the combined species, they would specify a species as "Blue Grouse (Dusky/Sooty))" later on in the `prepare_data()` stage?

Exactly. For the CWS, we analyse both and let the users choose which version they want to use. There are some situations where the changes in taxonomy over time have affected the way observers report their data. So in some situations the split species make sense to interpret, in others the lumped group is more meaningful.

**Comment by steffilazerte** [comment]
Great thanks!
